asl-current-142-bld184

diff --git a/tests/testall b/tests/testall
--- a/tests/testall
+++ b/tests/testall
@@ -10,20 +10,30 @@ if [ "$1" = "" ]; then
 else
  SUBDIRS="$1"
 fi
+if [ "$V" != "1" ]; then
+  QUIET="-q"
+fi
+
 for t in $SUBDIRS; do
  if test -f $t/$t.asm; then
  if test -f $t/$t.ori; then
  if cd $t ; then
  {
-  cat $t.doc
+  if test "$V" = "1"; then
+   cat $t.doc
+  fi
   # valgrind --leak-check=yes  ...
-  ${RUNCMD} ../../${OBJDIR}asl `cat asflags` -Werror -i ../../include $t.asm | tee $t.log
-  ${RUNCMD} ../../${OBJDIR}p2bin -k -l 0 -r 0x-0x $t
-  echo +---------------------------------------------------------------+
+  ${RUNCMD} ../../${OBJDIR}asl `cat asflags` $QUIET -Werror -i ../../include $t.asm | tee $t.log
+  ${RUNCMD} ../../${OBJDIR}p2bin $QUIET -k -l 0 -r 0x-0x $t
+  if test "$V" = "1"; then
+   echo +---------------------------------------------------------------+
+  fi
   if cmp $t.ori $t.bin; then
-   echo "Test $t succeeded!"
-   SUMPASS=`expr $SUMPASS + 1`
+   if test "$V" = "1"; then
+    echo "Test $t succeeded!"
+   fi
    echo "$t : OK" >> ../../testlog
+   SUMPASS=`expr $SUMPASS + 1`
   else
    echo "Test $t failed!"
    SUMFAIL=`expr $SUMFAIL + 1`
@@ -31,7 +41,9 @@ for t in $SUBDIRS; do
   fi
   grep assembly $t.log >> ../../testlog
   grep Assemblierzeit $t.log >> ../../testlog
-  echo +---------------------------------------------------------------+
+  if test "$V" = "1"; then
+   echo +---------------------------------------------------------------+
+  fi
   rm -f $t.bin
   rm -f $t.log
   rm -f $t.h
@@ -48,4 +60,14 @@ for t in $SUBDIRS; do
 done
 echo "successes: $SUMPASS" >> ../testlog
 echo "failures : $SUMFAIL" >> ../testlog
-cat ../testlog
+if [ "$V" = "1" ] || [ "$SUMFAIL" != "0" ]; then
+  cat ../testlog
+else
+  echo "successes: $SUMPASS"
+  echo "failures : $SUMFAIL"
+fi
+if test "$SUMFAIL" = "0"; then
+  exit 0
+else
+  exit 1
+fi
