Cleaning up testall script

diff --git a/tests/testall b/tests/testall
--- a/tests/testall
+++ b/tests/testall
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 echo executing self tests...
 echo "=================================================================" > ../testlog
@@ -6,72 +6,62 @@ echo "Summaric results:" >> ../testlog
 SUMPASS="0"
 SUMFAIL="0"
 if [ "$1" = "" ]; then
- SUBDIRS=t_*
+    SUBDIRS="t_*"
 else
- SUBDIRS="$1"
+    SUBDIRS="$1"
 fi
 if [ "$V" != "1" ]; then
-  QUIET="-q"
+    QUIET="-q"
 fi
 
 for t in $SUBDIRS; do
- if test -f $t/$t.asm; then
- if test -f $t/$t.ori; then
- if cd $t ; then
- {
-  if test "$V" = "1"; then
-   cat $t.doc
-  fi
-  # valgrind --leak-check=yes  ...
-  ${RUNCMD} ../../${OBJDIR}asl `cat asflags` $QUIET -Werror -i ../../include $t.asm | tee $t.log
-  ${RUNCMD} ../../${OBJDIR}p2bin $QUIET -k -l 0 -r 0x-0x $t
-  if test "$V" = "1"; then
-   echo +---------------------------------------------------------------+
-  fi
-  if cmp $t.ori $t.bin; then
-   if test "$V" = "1"; then
-    echo "Test $t succeeded!"
-   fi
-   echo "$t : OK" >> ../../testlog
-   SUMPASS=`expr $SUMPASS + 1`
-  else
-   echo "Test $t failed!"
-   SUMFAIL=`expr $SUMFAIL + 1`
-   echo "$t : failed" >> ../../testlog
-   echo "$t : expected" >> ../../testlog
-   od -tx1 -An $t.ori >> ../../testlog
-   echo "$t : obtained" >> ../../testlog
-   od -tx1 -An $t.bin >> ../../testlog
-  fi
-  grep assembly $t.log >> ../../testlog
-  grep Assemblierzeit $t.log >> ../../testlog
-  if test "$V" = "1"; then
-   echo +---------------------------------------------------------------+
-  fi
-  rm -f $t.bin
-  rm -f $t.log
-  rm -f $t.h
-  cd ..
- }
- else
- {
-  echo "$t : no such test" >> ../testlog
-  SUMFAIL=`expr $SUMFAIL + 1`
- }
- fi
- fi
- fi
+    if test -f "$t/$t.asm"; then
+        if test -f "$t/$t.ori"; then
+            if cd "$t" ; then
+                if test "$V" = "1"; then
+                    cat "$t.doc"
+                fi
+                # valgrind --leak-check=yes  ...
+                read -ra args < <(cat asflags)
+                ${RUNCMD} "../../${OBJDIR}asl" "${args[@]}" $QUIET -Werror -i ../../include "$t.asm" | tee "$t.log"
+                ${RUNCMD} "../../${OBJDIR}p2bin" $QUIET -k -l 0 -r 0x-0x "$t"
+                if test "$V" = "1"; then
+                    echo +---------------------------------------------------------------+
+                fi
+                if cmp -b "$t.ori" "$t.bin"; then
+                    if test "$V" = "1"; then
+                        echo "Test $t succeeded!"
+                    fi
+                    echo "$t : OK" >> ../../testlog
+                    SUMPASS=$(( SUMPASS + 1 ))
+                else
+                    echo "Test $t failed!"
+                    SUMFAIL=$(( SUMFAIL + 1 ))
+                    { echo "$t : failed"; echo "$t : expected"; od -tx1 -v -An "$t.ori"; echo "$t : obtained"; od -tx1 -v -An "$t.bin"; } >> ../../testlog
+                fi
+                grep assembly "$t.log" >> ../../testlog
+                grep Assemblierzeit "$t.log" >> ../../testlog
+                if test "$V" = "1"; then
+                    echo +---------------------------------------------------------------+
+                fi
+                rm -f "$t.bin" "$t.log" "$t.h"
+                cd ..
+            else
+                echo "$t : no such test" >> ../testlog
+                SUMFAIL=$(( SUMFAIL + 1 ))
+            fi
+        fi
+    fi
 done
-echo "successes: $SUMPASS" >> ../testlog
-echo "failures : $SUMFAIL" >> ../testlog
+{ echo "successes: $SUMPASS"; echo "failures : $SUMFAIL"; } >> ../testlog
 if [ "$V" = "1" ] || [ "$SUMFAIL" != "0" ]; then
-  cat ../testlog
+    cat ../testlog
 else
-  echo "successes: $SUMPASS"
-  echo "failures : $SUMFAIL"
+    echo "successes: $SUMPASS"
+    echo "failures : $SUMFAIL"
 fi
 if test "$SUMFAIL" = "0"; then
-  exit 0
+    exit 0
 else
-  exit 1
+    exit 1
 fi
